import json
import logging
from pathlib import Path
from transformers import AutoTokenizer

from display_results import ResultsApp
from model.dataset_builder import DatasetBuilder

VERBOSE = False
DATA_BASE_DIR = Path("holdout") # command line arg
PDF_DIR = DATA_BASE_DIR / "raw"
PREPROCESSING_OUTPUT_DIR = DATA_BASE_DIR / "processed"
LABELS_DIR = DATA_BASE_DIR / "labels/aop_raw" # maybe restructure to fit rest of pipeline
SCORED_EVENTS_DIR = DATA_BASE_DIR / "labels/scored" # maybe restructure to fit rest of pipeline
DIVIDED_MD_DIR = PREPROCESSING_OUTPUT_DIR / "divided_markdown" # to remove, get from PREPROCESSING_OUTPUT_DIR / "divided_markdown"
TRAIN_TEST_BASE_DIR = Path("train/dataset/") # command line arg
FINAL_JSON_TRAIN = TRAIN_TEST_BASE_DIR / "train_fold_0.jsonl"
FINAL_JSON_TEST = TRAIN_TEST_BASE_DIR / "test_fold_0.jsonl"
SPLIT_INFO_PATH = TRAIN_TEST_BASE_DIR / "split_info_fold_2.json" # generated by DatasetBuilder, used by PredEvaluator
EVAL_RESULTS_BASE_DIR = Path("train/results_7/llama/fold_2/epoch8") # command line arg
EVAL_RESULTS_JSONL = EVAL_RESULTS_BASE_DIR / "eval_preds.jsonl"
EVAL_ANALYSIS_RESULT = EVAL_RESULTS_BASE_DIR / "eval_analysis.txt"
EVAL_RESULTS_FULL_ANALYSIS_DIR = EVAL_RESULTS_BASE_DIR / "full_analysis"
RAG_INDEX_PATH = "rag/aop_rag_index.json"



def check_token_lengths(
    train_path: str,
    test_path: str,
    max_tokens: int = BIOMISTRAL_CONTEXT_TOKENS,
    tokenizer=TOKENIZER,
) -> None:
    """
    Reads train/test JSONL files, tokenizes each example using the chat template,
    and reports any entries exceeding max_tokens.
    """
    for split_name, path in [("train", train_path), ("test", test_path)]:
        data = []
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    data.append(json.loads(line))

        lengths = []
        over_limit = []

        for i, example in enumerate(data):
            messages = example["messages"]
            full_str = tokenizer.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=False
            )
            n_tokens = len(tokenizer.encode(full_str))
            lengths.append(n_tokens)

            if n_tokens > max_tokens:
                over_limit.append((i, n_tokens))

        print(f"\n--- {split_name} ({len(data)} examples) ---")
        print(f"  Token range: {min(lengths)}-{max(lengths)}, median: {sorted(lengths)[len(lengths)//2]}")
        print(f"  Exceeding {max_tokens}: {len(over_limit)}/{len(data)}")
        for idx, n in over_limit:
            print(f"    example {idx}: {n} tokens (+{n - max_tokens} over)")

def score_events(dirs):
  from event_scorer import EventScorer
  divided_md_files = list(paths["divided_markdown"].glob("*.json"))
  raw_labels_files = list(paths["raw_labels"].glob("*.txt"))
  with EventScorer(
    divided_md_files=divided_md_files,
    output_dir=paths["scored_labels"],
    label_files=raw_labels_files,
  ) as scorer:
    scorer.run_scoring()

def build_dataset(dirs, test_ratio=0.15, empty_ratio=1.0, k_folds=5, seed=42):
  from model.dataset_builder import DatasetBuilder
  with DatasetBuilder(
    input_dir=paths["scored_labels"],
    output_train_path=FINAL_JSON_TRAIN,
    output_test_path=FINAL_JSON_TEST
  ) as builder:
    builder.build_biomistral_chunk_dataset(
      test_ratio=test_ratio,
      empty_ratio=empty_ratio,
      k_folds=k_folds,
      seed=seed
    )

def test(do_scoring=False, do_dataset=False, do_eval_analysis=True):
  from event_scorer import PredEvaluator, EventScorer, DatasetBuilder
  
  if do_dataset:
      with DatasetBuilder(input_dir=SCORED_EVENTS_DIR, output_train_path=FINAL_JSON_TRAIN, output_test_path=FINAL_JSON_TEST) as builder:
          builder.build_biomistral_chunk_dataset(
              test_ratio=0.15,
              empty_ratio=1.0,   # Keep all empty chunks as negatives
              k_folds=5,
              seed=42
          )
      
  if do_eval_analysis:
      with PredEvaluator(
        EVAL_RESULTS_JSONL, 
        output_path=EVAL_ANALYSIS_RESULT, 
        full_eval_analysis_folder_path=EVAL_RESULTS_FULL_ANALYSIS_DIR, 
        split_info_path=SPLIT_INFO_PATH
      ) as evaluator:
            evaluator.analyze_eval_jsonl()
            evaluator.analyze_eval_jsonl_per_paper()


if __name__ == "__main__":
  # Parse command line arguments
  import argparse
  parser = argparse.ArgumentParser(description="AOP Events Extractor (Dev Tools)")
  parser.add_argument("--do_scoring", action="store_true",
                      help="Run event scoring")
  parser.add_argument("--do_dataset", action="store_true",
                      help="Build dataset for model training")
  parser.add_argument("--do_eval_analysis", action="store_true",
                      help="Analyze evaluation results")
  parser.add_argument("--do_token_check", action="store_true",
                      help="Analyze token lengths in train/test datasets")
  
  args = parser.parse_args()

  # Get config values from config.ini
  import configparser
  from model.common import PROMPT_INSTRUCTIONS
  config = configparser.ConfigParser()
  config.read("config.ini")
  model = config.get("DEFAULT", "model")
  model_weights = config.get("DEFAULT", "model_weights")
  model_context_tokens = config.getint("DEFAULT", "model_context_tokens")
  min_chunk_tokens = config.getint("DEFAULT", "min_chunk_tokens")
  target_chunk_tokens = config.getint("DEFAULT", "target_chunk_tokens")
  max_chunk_tokens = config.getint("DEFAULT", "max_chunk_tokens")
  reserved_output_tokens = config.getint("DEFAULT", "reserved_output_tokens")
  safety_margin_tokens = config.getint("DEFAULT", "safety_margin_tokens")
  dataset_test_ratio = config.getfloat("DATASET", "test_ratio")
  dataset_empty_ratio = config.getfloat("DATASET", "empty_ratio")
  dataset_k_folds = config.getint("DATASET", "k_folds")
  dataset_seed = config.getint("DATASET", "seed")


  paths = {
    "input_pdf": Path(config.get("DIRECTORIES", "input_pdf_dir")),
    "raw_markdown": Path(config.get("DIRECTORIES", "raw_markdown_dir")),
    "clean_markdown": Path(config.get("DIRECTORIES", "clean_markdown_dir")),
    "divided_markdown": Path(config.get("DIRECTORIES", "divided_markdown_dir")),
    "extracted_events": Path(config.get("DIRECTORIES", "extracted_events_dir")),
    "scored_events": Path(config.get("DIRECTORIES", "scored_events_dir")),
    "raw_labels": Path(config.get("DIRECTORIES", "raw_labels_dir")),
    "scored_labels": Path(config.get("DIRECTORIES", "scored_labels_dir")),
  }

  if not (args.do_scoring or args.do_dataset or args.do_eval_analysis or args.do_token_check):
      print("No action specified. Use --do_scoring, --do_dataset, --do_eval_analysis, and/or --do_token_check.")

  if args.do_scoring:
      score_events(paths)

  if args.do_dataset:
      build_dataset(
        paths, 
        test_ratio=dataset_test_ratio, 
        empty_ratio=dataset_empty_ratio, 
        k_folds=dataset_k_folds, 
        seed=dataset_seed
      )
  
  if args.do_token_check:
      check_token_lengths(
        train_path=FINAL_JSON_TRAIN,
        test_path=FINAL_JSON_TEST,
        max_tokens=model_context_tokens - reserved_output_tokens - safety_margin_tokens,
        tokenizer=AutoTokenizer.from_pretrained(model_weights)
      )


  
